export const ARCHIVE_BUTTON_LABEL = 'Archive'
export const DELETE_BUTTON_LABEL = 'Delete'
export const DISCARD_BUTTON_LABEL = 'Discard'
export const EMAILS_SELECTED_SINGLE = 'email selected'
export const EMAILS_SELECTED_PLURAL = 'emails selected'
