export const TO_LABEL = 'To'
export const SUBJECT_LABEL = 'Subject'
export const BODY_LABEL = 'Body'
export const SEND_BUTTON = 'Send'
export const CANCEL_BUTTON = 'Cancel'
export const COMPOSE = 'Compose'
export const EMAIL_WARNING = 'Please enter a valid email'
