export const LOADING_TEXT = 'Loading'
export const BUTTON_BACK = 'Back'
export const NOTHING_TO_SEE = 'Nothing to see here'
export const NO_SUBJECT = '(No subject)'
export const LOAD_MORE = 'Load more messages'
export const MAX_RESULTS = 20
export const NO_MORE_RESULTS = "You've reached the end."
export const UNREAD_LABEL = 'UNREAD'
export const ARCHIVE_LABEL = 'ARCHIVE'
export const SEARCH_LABEL = 'SEARCH'
export const INBOX_LABEL = 'INBOX'
export const CORE_STATUS_SORTING = 'isSorting'
export const CORE_STATUS_SEARCHING = 'isSearching'
export const CORE_STATUS_FOCUSED = 'isFocused'
