export const LOADING_TEXT = 'Loading'
export const BUTTON_BACK = 'Back'
export const NOTHING_TO_SEE = 'Nothing to see here'
export const NO_SUBJECT = '(No subject)'
export const UNREAD_LABEL = 'UNREAD'
export const LOAD_OLDER = 'Load older messages'
export const MAX_RESULTS = 20
export const NO_MORE_RESULTS = "You've reached the end."
export const ARCHIVE_LABEL = 'ARCHIVE'
