export const white = '#f0f0f0'
export const slightWhite = '#f7f7f7'
export const greyHover = '#E2E2E2'
export const greyBorder = '#ededed'
export const colorBlack = '#1c1c1c'
export const colorPurple = '#8e23d1'
export const colorPurpleSoft = '#e4dee7'
