name: Other
description: Use this, Please DO NOT create blank issues
title: "[Other]: "
labels: ["🚦 status: awaiting triage"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what this issue is about.
      placeholder: If you are not using the wiki tab, please hide it
    validations:
      required: true

  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false

  - type: checkboxes
    id: guidelines
    attributes:
      label: Code of Conduct
      options:
        - label: I agree to follow this project's [Code of Conduct](https://github.com/Elysium-Labs-EU/juno-core/blob/dev/CODE_OF_CONDUCT.md)
          required: true
